namePrefix: kustomize-
buildMetadata: [managedByLabel, originAnnotations, transformerAnnotations]
namespace: alabala
commonAnnotations:
  argocd.argoproj.io/tracking-id: YWxhYmFsYQ==
labels:
  - pairs:
      app.kubernetes.io/part-of: kustomize-guestbook
    includeSelectors: false # <-- false by default
    includeTemplates: true # <-- false by default
configMapGenerator:
  - name: guestbook-cm
    files:
      - index2.html
resources:
  - guestbook-ui-deployment.yaml
  - guestbook-ui-svc.yaml
  - guestbook-ui-ing.yaml
  - safari-sf.yml
  - safari-dp.yml
  - safari-pvc-dp.yml
  - safari-pvc-st.yml
  - safari-ing.yml
  - safari-svc.yml
  - default-limit-range.yml
  - default-pod-quota.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
