apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: safari
  name: safari
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safari
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: safari
    spec:
      volumes: # add
        - name: data # add
          persistentVolumeClaim: # add
            claimName: safari-pvc-dp # add
      containers:
        - image: httpd:2.4.41-alpine
          name: container
          volumeMounts: # add
            - name: data # add
              mountPath: /tmp/safari-data # add
