apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: safari-dp
    app.kubernetes.io/name: safari-dp
    app.kubernetes.io/instance: safari-dp
    resize: v1
  name: safari-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safari-dp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: safari-dp
    spec:
      containers:
        - image: httpd:2.4.41-alpine
          name: container
          volumeMounts: 
            - name: data
              mountPath: /tmp/safari-data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: safari-pvc-dp
