kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: safari
    app.kubernetes.io/instance: safari
  name: safari-pvc-dp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
    storageClassName: azurefile
