kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: safari
    app.kubernetes.io/instance: safari
  name: safari-pvc-st
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
