apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: safari-ing-dp
    app.kubernetes.io/instance: safari-ing-dp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: safari-ing-dp
spec:
  rules:
  - host: safari-dp.foo.bar
    http:
      paths:
      - backend:
          service:
            name: safari-svc-dp
            port:
              number: 80
        pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: safari-ing-st
    app.kubernetes.io/instance: safari-ing-st
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: safari-ing-st
spec:
  rules:
  - host: safari-st.foo.bar
    http:
      paths:
      - backend:
          service:
            name: safari-svc-st
            port:
              number: 80
        pathType: ImplementationSpecific
