kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: safari-pvc-dp
  labels:
    app.kubernetes.io/instance: alabala
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
