apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: safari
  name: safari
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safari
  serviceName: "safari-svc"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: safari
    spec:
      containers:
        - image: httpd:2.4.41-alpine
          name: container
          volumeMounts:
            - name: safari-pvcl
              mountPath: /tmp/safari-data
  volumeClaimTemplates:
    - metadata:
        name: safari-pvcl
        labels:
          app.kubernetes.io/instance: alabala
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: "default"
